# Generated by Django 4.1.12 on 2024-01-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_dob_profile_gender_profile_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(blank=True, null=True, upload_to='images/users/'),
        ),
    ]
