# Generated by Django 4.1.12 on 2023-12-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(null=True, upload_to='assetimages/user/'),
        ),
    ]
