# Generated by Django 4.1.12 on 2023-12-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(null=True, upload_to='images/users/'),
        ),
    ]
