# Generated by Django 4.1.12 on 2024-01-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neworder',
            name='order_no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='order_status',
            field=models.CharField(choices=[('New', 'New'), ('Active', 'Active'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Done', 'Done')], max_length=20),
        ),
        migrations.AlterField(
            model_name='neworder',
            name='project_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
