# Generated by Django 4.1.12 on 2024-01-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_neworder_order_no_alter_neworder_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastorderno',
            name='order_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
