# Generated by Django 4.1.12 on 2024-01-05 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_lastorderno_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='new_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neworder', to='clients.neworder'),
        ),
    ]
