# Generated by Django 4.1.12 on 2024-01-05 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_orderitem_new_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastOrderNo',
        ),
    ]
