# Generated by Django 4.1.12 on 2024-01-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_delete_lastorderno'),
    ]

    operations = [
        migrations.AddField(
            model_name='neworder',
            name='assets',
            field=models.ImageField(blank=True, null=True, upload_to='files/orderfiles/'),
        ),
    ]
