# Generated by Django 4.1.12 on 2024-01-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_neworder_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neworder',
            name='assets',
            field=models.ImageField(blank=True, null=True, upload_to='files/order_files/'),
        ),
    ]
