# Generated by Django 4.1.12 on 2024-01-07 18:11

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_neworder_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neworder',
            name='assets',
            field=models.ImageField(blank=True, null=True, upload_to=clients.models.custom_upload_to),
        ),
    ]
