# Generated by Django 4.1.12 on 2024-01-03 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_rename_item_services_service_company_license_number_and_more'),
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_department', to='company.company'),
        ),
        migrations.AddField(
            model_name='position',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_position', to='staffs.department'),
        ),
    ]
