# Generated by Django 4.1.12 on 2024-01-03 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_department_company_position_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
    ]
