# Generated by Django 4.1.12 on 2023-12-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_staff_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_image',
            field=models.ImageField(null=True, upload_to='files/staff_assets/staff_photos'),
        ),
    ]
