# Generated by Django 4.1.12 on 2024-01-01 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=30)),
                ('logo', models.FileField(blank=True, null=True, upload_to='files/company_assets/')),
                ('tax_number', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField()),
                ('telephone', models.CharField(blank=True, max_length=12, null=True)),
                ('mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('founded_on', models.DateField(blank=True, null=True)),
                ('company_mission', models.TextField(blank=True, null=True)),
                ('company_vision', models.TextField(blank=True, null=True)),
                ('company_values', models.TextField(blank=True, null=True)),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('business_description', models.TextField(blank=True, null=True)),
                ('partnerships_affiliations', models.TextField(blank=True, null=True)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('legal_contacts', models.TextField(blank=True, null=True)),
                ('emergency_contacts', models.TextField(blank=True, null=True)),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='business_types', to='company.businesstype', verbose_name='BusinessType')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=50, verbose_name='Policy Number')),
                ('provider_name', models.CharField(max_length=100, verbose_name='Insurance Provider')),
                ('start_date', models.DateField(verbose_name='Coverage Start Date')),
                ('end_date', models.DateField(verbose_name='Coverage End Date')),
                ('insured_person_name', models.CharField(max_length=100, verbose_name='Insured Person Name')),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coverage Amount')),
            ],
            options={
                'verbose_name': 'Insurance Information',
                'verbose_name_plural': 'Insurance Information',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=100, verbose_name='Profile Name')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('x', 'X'), ('instagram', 'Instagram'), ('snapchat', 'Snapchat'), ('tiktok', 'Tiktok')], max_length=20, verbose_name='Social Media Platform')),
                ('profile_url', models.URLField(verbose_name='Profile URL')),
                ('followers_count', models.IntegerField(verbose_name='Followers Count')),
                ('date_joined', models.DateField(verbose_name='Date Joined')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialmedia', to='company.company')),
            ],
            options={
                'verbose_name': 'Social Media Profile',
                'verbose_name_plural': 'Social Media Profiles',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_services', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='PricingStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_name', models.CharField(max_length=255)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_structure', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='OwnershipInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_details', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_currency', models.CharField(choices=[('usd', 'USD - United States Dollar'), ('eur', 'EUR - Euro'), ('gbp', 'GBP - British Pound'), ('inr', 'INR - Indian Rupee'), ('qar', 'QAR - Qatar Riyal')], max_length=3, verbose_name='Preferred Currency')),
                ('conversion_rate', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Conversion Rate')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currency_preferences', to='company.company')),
            ],
            options={
                'verbose_name': 'Currency Preferences',
                'verbose_name_plural': 'Currency Preferences',
            },
        ),
        migrations.CreateModel(
            name='ClientTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('testimonial_text', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_testimonial', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('branch_name', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('upi_number', models.CharField(blank=True, max_length=13, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=25, null=True)),
                ('primary', models.BooleanField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='company.company')),
            ],
        ),
    ]
