# Generated by Django 4.1.12 on 2024-01-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
